language: scala

scala:
   - 2.12.8
   
jdk:
   - openjdk8

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

# https://github.com/olafurpg/sbt-ci-release#travisyml
before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: test
    - env: TEST="all"
      script: 
        - sbt ++$TRAVIS_SCALA_VERSION "test"
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'] # dont sonar PRs
    - stage: release
      script: sbt ci-release
    
notifications:
  email:
    - sakib@sake.ba


addons:
  sonarcloud:
    organization: "sake92-github"
    token:
      secure: $SONAR_TOKEN


